### ISSUE TITLE
RemoteStorage integration - please ping me

### ISSUE THREAD

**Issue by theWebalyst** [icidasset/isotach#42]
In working on a fork of RS.js to use SAFE Network (see maidsafe.net) as a backend and to test /demo that in gathering together as many RS compatible apps as I can. So would like to include o-r.

Please let me know (here) when you have a version working with RS. Thanks. Mark

**Comment by icidasset** [comment]
Thanks Mark, will let you know!

**Comment by icidasset** [comment]
@theWebalyst I added basic remoteStorage support, meaning that you can authenticate using remoteStorage and it keeps your settings and stuff in there. Still needs a lot of testing though.

**Comment by theWebalyst** [comment]
Yes, great I saw 👍  I've made a note to try it with my SAFE Network RS.js fork but I'm still based on RS.js 0.14 and so will need to update to 1.0 first. Will let you know when I have something in case you want to try it. 

You'll need an invite to the SAFE Alpha if you do so you might want to get on the [SAFE forum](https://safenetforum.org) first as you need to read enough to reach Trust Level 1 (Basic User) to get an invite.
